title   microarch (%ARCH%, UEFI)
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=2G console=tty0 console=ttyS0,115200n8 quiet
